import { useCallback,useEffect,useRef,useState } from 'react';
import { router } from 'expo-router';
import { Pressable,StyleSheet,Text,View } from 'react-native';
import { Button,Notice,Screen,styles } from '../../src/components/ui';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadState,useProductData } from '../../src/components/product';
import { completeMove,getGardenState,getMove,getTodayMove,getProgram,type Move } from '../../src/features/product';
import { sessionStorage } from '../../src/lib/storage';
import { useAuth } from '../../src/providers/AuthProvider';
const chapters=['Notice each other again','Add a little surprise','Turn toward each other','Keep what works'];
export default function Today(){const {session}=useAuth();const load=useCallback(async()=>{const program=await getProgram(session!.user.id);const garden=await getGardenState();const move:Move|null=garden.bloom?null:await getTodayMove(session!.user.id);return{program,garden,move}},[session!.user.id]);const state=useProductData(load);const locked=useRef(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [joinIntro,setJoinIntro]=useState(false);
 useEffect(()=>{let active=true;const program=state.data?.program;if(!program||program.role!=='member_b'||program.joinedDay<=1)return;const key=`same-side.join-intro.${session!.user.id}.${program.relationshipId}`;void sessionStorage.getItem(key).then(value=>{if(active&&!value)setJoinIntro(true);});return()=>{active=false};},[state.data?.program,session]);
 async function dismissJoinIntro(){const program=state.data?.program;if(!program)return;await sessionStorage.setItem(`same-side.join-intro.${session!.user.id}.${program.relationshipId}`,'1');setJoinIntro(false);}
 async function complete(){if(locked.current||!state.data?.move)return;locked.current=true;setBusy(true);setError(null);try{await completeMove(state.data.move.id);await state.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{locked.current=false;setBusy(false);}}
 async function oneMore(){const current=state.data?.move;if(locked.current||!current||current.status!=='completed'||current.slot>=2)return;locked.current=true;setBusy(true);setError(null);try{await getMove(current.slot+1);await state.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{locked.current=false;setBusy(false);}}
 const move=state.data?.move;const program=state.data?.program;const afterRoutine=!!program&&program.day>28;const week=move?Math.min(4,Math.max(1,Math.ceil(move.program_day/7))):program?.week??1;const primary=!move||move.slot===0;const paired=program?.memberCount===2;const early=!!program&&program.day<=3;const remaining=move?Math.max(0,2-move.slot):0;
 return <Screen compact><AppHeader/><LoadState {...state}/>{!state.loading&&!state.error&&program&&joinIntro&&<View style={[styles.card,s.joinCard]}><Text style={styles.eyebrow}>You’re joining what’s already growing</Text><Text style={[styles.cardTitle,{fontSize:25,lineHeight:31}]}>{program.day>28?'The Routine has already unfolded.':`You’re joining on Day ${program.day}.`}</Text><Text style={styles.body}>{program.day>28?'There’s nothing to catch up on. Start with a small move today and grow the same flower from here.':'There’s nothing you missed and nothing to make up. You begin with today’s move, in the same shared garden.'}</Text><Button label="Start from today" onPress={()=>{void dismissJoinIntro();}}/></View>}
 {!state.loading&&!state.error&&program&&state.data?.garden.bloom&&<View style={s.completeWrap}><Text style={styles.eyebrow}>YOUR GARDEN · IN BLOOM</Text><Text style={[styles.title,s.completeTitle]}>You grew this together.</Text><Text style={[styles.body,s.completeBody]}>The Routine is complete, and your shared flower has reached full bloom. Nothing was lost on the days you were away.</Text><Button label="Celebrate what you grew" onPress={()=>router.push('/routine-complete')}/><Pressable accessibilityRole="button" onPress={()=>router.navigate('/garden')} style={s.textAction}><Text style={s.textActionLabel}>See your garden →</Text></Pressable></View>}
 {!state.loading&&!state.error&&move&&program&&!joinIntro&&<><View style={s.context}><Text style={styles.eyebrow}>{afterRoutine?'THE ROUTINE · COMPLETE':`THE ROUTINE · WEEK ${week} OF 4`}</Text><Text style={s.chapter}>{afterRoutine?'Keep growing at your own pace':chapters[week-1]}</Text></View>
  <View style={[styles.card,s.moveCard]}><View style={s.row}><Text style={[styles.eyebrow,s.moveEyebrow]}>{afterRoutine?'FOR YOUR GARDEN':primary?'FOR YOU TODAY':'YOUR EXTRA MOVE'}</Text><View style={s.pill}><Text style={styles.small}>{move.task_minutes} min</Text></View></View><Text style={[styles.cardTitle,s.moveTitle]}>{move.task_title}</Text><Text style={[styles.body,s.moveBody]}>{move.task_body}</Text>{early&&primary&&<Text style={s.privacy}>{paired?(program.partnerName?`${program.partnerName} gets a different move. What you create grows in the same flower.`:'Your partner gets a different move. What you create grows in the same flower.'):'This one is just for you. You can invite your partner whenever you’re ready.'}</Text>}
   {move.status==='completed'?<View style={s.done}><Text style={s.doneTitle}>Done. A little something just grew.</Text><Text style={s.doneBody}>{paired?'Your move quietly became part of the flower you share.':'Your move is now part of your flower.'}</Text></View>:<Button label="I did it" busy={busy} onPress={()=>{void complete();}}/>}
  </View>
  {move.status==='completed'&&move.slot<2&&<View style={s.bonusCard}><View style={{flex:1}}><Text style={s.bonusKicker}>FEEL LIKE DOING A LITTLE MORE?</Text><Text style={s.bonusTitle}>Get another private move</Text><Text style={s.bonusBody}>Optional. You have {remaining} more {remaining===1?'move':'moves'} available today.</Text></View><Button label={busy?'A moment…':'Give me another move'} secondary disabled={busy} onPress={()=>{void oneMore();}}/><Pressable accessibilityRole="button" onPress={()=>router.navigate('/garden')} style={s.textAction}><Text style={s.textActionLabel}>Or see your flower →</Text></Pressable></View>}
  {move.status==='completed'&&move.slot>=2&&<View style={s.finished}><Text style={s.bonusTitle}>That’s plenty for today.</Text><Pressable accessibilityRole="button" onPress={()=>router.navigate('/garden')} style={s.textAction}><Text style={s.textActionLabel}>See your flower →</Text></Pressable></View>}
  {error&&<><Notice>{error}</Notice><Button label="Try again" secondary disabled={busy} onPress={()=>{setError(null);void state.refresh();}}/></>}</>}</Screen>;
}
const s=StyleSheet.create({joinCard:{marginTop:28,padding:22,gap:12},context:{marginTop:24,marginBottom:12,gap:3},chapter:{fontFamily:'Georgia',fontSize:17,lineHeight:22,color:'#667C6A'},moveCard:{padding:24,borderRadius:28,borderWidth:1,borderColor:'#C8D3C5',backgroundColor:'#FCFAF5'},moveEyebrow:{color:'#405448',letterSpacing:1.6},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},pill:{backgroundColor:'#EEF1E9',borderRadius:999,paddingHorizontal:11,paddingVertical:7},moveTitle:{fontSize:31,lineHeight:35,marginTop:18,marginBottom:12},moveBody:{fontSize:17,lineHeight:25,marginBottom:18},privacy:{fontSize:12,lineHeight:18,color:'#8A8278',marginBottom:18},done:{gap:7,paddingTop:4},doneTitle:{fontFamily:'Georgia',fontSize:20,lineHeight:25,color:'#34483C'},doneBody:{fontSize:13,lineHeight:19,color:'#847C72'},bonusCard:{marginTop:12,padding:18,borderRadius:22,backgroundColor:'#F4EFE7',gap:12},bonusKicker:{fontSize:10,lineHeight:14,letterSpacing:1.4,fontWeight:'700',color:'#728978'},bonusTitle:{fontFamily:'Georgia',fontSize:21,lineHeight:26,color:'#34483C',marginTop:3},bonusBody:{fontSize:13,lineHeight:19,color:'#847C72',marginTop:4},finished:{marginTop:14,padding:18,borderRadius:20,backgroundColor:'#F4EFE7',gap:6},textAction:{minHeight:40,justifyContent:'center',alignSelf:'flex-start'},textActionLabel:{fontSize:13,fontWeight:'700',color:'#667C6A'},completeWrap:{marginTop:72,gap:18},completeTitle:{fontSize:40,lineHeight:44,letterSpacing:-1.2},completeBody:{lineHeight:24,marginBottom:8}});
