import { useCallback,useEffect,useRef,useState } from 'react';
import { router } from 'expo-router';
import { Pressable,StyleSheet,Text,View } from 'react-native';
import { Button,Notice,Screen,styles } from '../../src/components/ui';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadState,useProductData } from '../../src/components/product';
import { completeMove,getGardenState,getMove,getTodayMove,getProgram,type Move } from '../../src/features/product';
import { sessionStorage } from '../../src/lib/storage';
import { useAuth } from '../../src/providers/AuthProvider';
const goals=[
 {title:'Notice each other again',body:'Bring small moments of attention back into everyday life.'},
 {title:'Add a little surprise',body:'Make ordinary days feel a little less automatic.'},
 {title:'Turn toward each other',body:'Create more moments of warmth, presence and connection.'},
 {title:'Keep what works',body:'Turn the small changes that helped into habits that can stay.'},
];
export default function Today(){const {session}=useAuth();const load=useCallback(async()=>{const program=await getProgram(session!.user.id);const garden=await getGardenState();const move:Move|null=garden.bloom?null:await getTodayMove(session!.user.id);return{program,garden,move}},[session!.user.id]);const state=useProductData(load);const locked=useRef(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [joinIntro,setJoinIntro]=useState(false);
 useEffect(()=>{let active=true;const program=state.data?.program;if(!program||program.role!=='member_b'||program.joinedDay<=1)return;const key=`same-side.join-intro.${session!.user.id}.${program.relationshipId}`;void sessionStorage.getItem(key).then(value=>{if(active&&!value)setJoinIntro(true);});return()=>{active=false};},[state.data?.program,session]);
 async function dismissJoinIntro(){const program=state.data?.program;if(!program)return;await sessionStorage.setItem(`same-side.join-intro.${session!.user.id}.${program.relationshipId}`,'1');setJoinIntro(false);}
 async function complete(){if(locked.current||!state.data?.move)return;locked.current=true;setBusy(true);setError(null);try{await completeMove(state.data.move.id);await state.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{locked.current=false;setBusy(false);}}
 async function oneMore(){const current=state.data?.move;if(locked.current||!current||current.status!=='completed'||current.slot>=2)return;locked.current=true;setBusy(true);setError(null);try{await getMove(current.slot+1);await state.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{locked.current=false;setBusy(false);}}
 const move=state.data?.move;const program=state.data?.program;const afterRoutine=!!program&&program.day>28;const goal=move?Math.min(4,Math.max(1,Math.ceil(move.program_day/7))):program?.week??1;const primary=!move||move.slot===0;const remaining=move?Math.max(0,2-move.slot):0;
 return <Screen compact><AppHeader/><LoadState {...state}/>{!state.loading&&!state.error&&program&&joinIntro&&<View style={[styles.card,s.joinCard]}><Text style={styles.eyebrow}>You’re joining what’s already growing</Text><Text style={[styles.cardTitle,{fontSize:25,lineHeight:31}]}>{program.day>28?'The Routine has already unfolded.':`You’re joining on Day ${program.day}.`}</Text><Text style={styles.body}>{program.day>28?'There’s nothing to catch up on. Start with a small move today and grow the same flower from here.':'There’s nothing you missed and nothing to make up. You begin with today’s move, in the same shared garden.'}</Text><Button label="Start from today" onPress={()=>{void dismissJoinIntro();}}/></View>}
 {!state.loading&&!state.error&&program&&state.data?.garden.bloom&&<View style={s.completeWrap}><Text style={styles.eyebrow}>YOUR GARDEN · IN BLOOM</Text><Text style={[styles.title,s.completeTitle]}>You grew this together.</Text><Text style={[styles.body,s.completeBody]}>The Routine is complete, and your shared flower has reached full bloom. Nothing was lost on the days you were away.</Text><Button label="Celebrate what you grew" onPress={()=>router.push('/routine-complete')}/><Pressable accessibilityRole="button" onPress={()=>router.navigate('/garden')} style={s.textAction}><Text style={s.textActionLabel}>See your garden →</Text></Pressable></View>}
 {!state.loading&&!state.error&&move&&program&&!joinIntro&&<><View style={s.context}><Text style={styles.eyebrow}>{afterRoutine?'THE ROUTINE · COMPLETE':`CURRENT GOAL · ${goal} OF 4`}</Text><Text style={s.chapter}>{afterRoutine?'Keep growing at your own pace':goals[goal-1].title}</Text></View>
  <View style={[styles.card,s.moveCard]}><View style={s.row}><Text style={[styles.eyebrow,s.moveEyebrow]}>{afterRoutine?'FOR YOUR GARDEN':primary?'FOR YOU TODAY':'YOUR EXTRA MOVE'}</Text><View style={s.pill}><Text style={styles.small}>{move.task_minutes} min</Text></View></View><Text style={[styles.cardTitle,s.moveTitle]}>{move.task_title}</Text><Text style={[styles.body,s.moveBody]}>{move.task_body}</Text>
   {move.status==='completed'?<View style={s.done}><View style={s.check}><Text style={s.checkText}>✓</Text></View><View style={{flex:1}}><Text style={s.doneTitle}>Done for today</Text><Text style={s.doneBody}>That small moment is now part of what you’re building together.</Text></View></View>:<Button label="I did it" busy={busy} onPress={()=>{void complete();}}/>}
  </View>
  {move.status==='completed'&&move.slot<2&&<View style={s.bonusCard}><View style={{flex:1}}><Text style={s.bonusKicker}>FEEL LIKE DOING A LITTLE MORE?</Text><Text style={s.bonusTitle}>Get another private move</Text><Text style={s.bonusBody}>Optional. You have {remaining} more {remaining===1?'move':'moves'} available today.</Text></View><Button label={busy?'A moment…':'Give me another move'} secondary disabled={busy} onPress={()=>{void oneMore();}}/><Pressable accessibilityRole="button" onPress={()=>router.navigate('/garden')} style={s.textAction}><Text style={s.textActionLabel}>Or see your flower →</Text></Pressable></View>}
  {move.status==='completed'&&move.slot>=2&&<View style={s.finished}><Text style={s.bonusTitle}>That’s plenty for today.</Text><Pressable accessibilityRole="button" onPress={()=>router.navigate('/garden')} style={s.textAction}><Text style={s.textActionLabel}>See your flower →</Text></Pressable></View>}
  {!afterRoutine&&<View style={s.pathCard}><Text style={s.pathKicker}>YOUR PATH</Text><Text style={s.pathTitle}>What you’re working toward</Text><View style={s.goalList}>{goals.map((item,index)=>{const n=index+1;const current=n===goal;const past=n<goal;return <View key={item.title} style={[s.goalRow,current&&s.goalCurrent]}><View style={[s.goalNumber,current&&s.goalNumberCurrent,past&&s.goalNumberPast]}><Text style={[s.goalNumberText,(current||past)&&s.goalNumberTextActive]}>{past?'✓':n}</Text></View><View style={{flex:1}}><Text style={[s.goalLabel,current&&s.goalLabelCurrent]}>{current?'CURRENT GOAL':past?'COMPLETED':n===goal+1?'NEXT GOAL':'LATER'}</Text><Text style={s.goalTitle}>{item.title}</Text>{(current||n===goal+1)&&<Text style={s.goalBody}>{item.body}</Text>}</View></View>})}</View></View>}
  {error&&<><Notice>{error}</Notice><Button label="Try again" secondary disabled={busy} onPress={()=>{setError(null);void state.refresh();}}/></>}</>}</Screen>;
}
const s=StyleSheet.create({joinCard:{marginTop:28,padding:22,gap:12},context:{marginTop:24,marginBottom:12,gap:3},chapter:{fontFamily:'Georgia',fontSize:17,lineHeight:22,color:'#667C6A'},moveCard:{padding:24,borderRadius:28,borderWidth:1,borderColor:'#C8D3C5',backgroundColor:'#FCFAF5'},moveEyebrow:{color:'#405448',letterSpacing:1.6},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},pill:{backgroundColor:'#EEF1E9',borderRadius:999,paddingHorizontal:11,paddingVertical:7},moveTitle:{fontSize:31,lineHeight:35,marginTop:18,marginBottom:12},moveBody:{fontSize:17,lineHeight:25,marginBottom:18},done:{marginTop:2,paddingTop:16,borderTopWidth:1,borderTopColor:'#D9E2D6',flexDirection:'row',alignItems:'center',gap:13},check:{width:38,height:38,borderRadius:19,backgroundColor:'#DDE9DA',alignItems:'center',justifyContent:'center'},checkText:{fontSize:22,lineHeight:24,fontWeight:'800',color:'#49644F'},doneTitle:{fontFamily:'Georgia',fontSize:20,lineHeight:25,color:'#34483C'},doneBody:{fontSize:13,lineHeight:19,color:'#847C72',marginTop:2},bonusCard:{marginTop:12,padding:18,borderRadius:22,backgroundColor:'#F4EFE7',gap:12},bonusKicker:{fontSize:10,lineHeight:14,letterSpacing:1.4,fontWeight:'700',color:'#728978'},bonusTitle:{fontFamily:'Georgia',fontSize:21,lineHeight:26,color:'#34483C',marginTop:3},bonusBody:{fontSize:13,lineHeight:19,color:'#847C72',marginTop:4},finished:{marginTop:14,padding:18,borderRadius:20,backgroundColor:'#F4EFE7',gap:6},textAction:{minHeight:40,justifyContent:'center',alignSelf:'flex-start'},textActionLabel:{fontSize:13,fontWeight:'700',color:'#667C6A'},pathCard:{marginTop:24,paddingTop:22,borderTopWidth:1,borderTopColor:'#DDD6C9'},pathKicker:{fontSize:10,lineHeight:14,letterSpacing:1.5,fontWeight:'700',color:'#728978'},pathTitle:{fontFamily:'Georgia',fontSize:23,lineHeight:29,color:'#34483C',marginTop:5,marginBottom:14},goalList:{gap:9},goalRow:{flexDirection:'row',gap:12,paddingVertical:12,paddingHorizontal:12,borderRadius:18,opacity:.64},goalCurrent:{backgroundColor:'#EEF1E9',opacity:1},goalNumber:{width:31,height:31,borderRadius:16,borderWidth:1,borderColor:'#D2CBC0',alignItems:'center',justifyContent:'center'},goalNumberCurrent:{backgroundColor:'#708873',borderColor:'#708873'},goalNumberPast:{backgroundColor:'#DDE9DA',borderColor:'#DDE9DA'},goalNumberText:{fontSize:12,fontWeight:'800',color:'#8B8379'},goalNumberTextActive:{color:'#FFFFFF'},goalLabel:{fontSize:9,lineHeight:12,letterSpacing:1.1,fontWeight:'800',color:'#91897F'},goalLabelCurrent:{color:'#667C6A'},goalTitle:{fontFamily:'Georgia',fontSize:17,lineHeight:22,color:'#34483C',marginTop:2},goalBody:{fontSize:12.5,lineHeight:18,color:'#817A72',marginTop:3},completeWrap:{marginTop:72,gap:18},completeTitle:{fontSize:40,lineHeight:44,letterSpacing:-1.2},completeBody:{lineHeight:24,marginBottom:8}});
