import { useCallback,useRef,useState } from 'react';
import { router } from 'expo-router';
import { Pressable,StyleSheet,Text,View } from 'react-native';
import { Button,Notice,Screen,styles } from '../../src/components/ui';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadState,useProductData } from '../../src/components/product';
import { completeMove,getMove,getTodayMove,getProgram } from '../../src/features/product';
import { useAuth } from '../../src/providers/AuthProvider';
const chapters=['Notice each other again','Add a little surprise','Turn toward each other','Keep what works'];const dayLabels=['M','T','W','T','F','S','S'];
export default function Today(){const {session}=useAuth();const load=useCallback(async()=>{const program=await getProgram(session!.user.id);return{program,move:await getTodayMove(session!.user.id)}},[session!.user.id]);const state=useProductData(load);const locked=useRef(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 async function complete(){if(locked.current||!state.data)return;locked.current=true;setBusy(true);setError(null);try{await completeMove(state.data.move.id);await state.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{locked.current=false;setBusy(false);}}
 async function oneMore(){const current=state.data?.move;if(locked.current||!current||current.status!=='completed'||current.slot>=2)return;locked.current=true;setBusy(true);setError(null);try{await getMove(current.slot+1);await state.refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Please try again.');}finally{locked.current=false;setBusy(false);}}
 const move=state.data?.move;const week=move?Math.min(4,Math.max(1,Math.ceil(move.program_day/7))):1;const dayInWeek=move?((move.program_day-1)%7)+1:1;const primary=!move||move.slot===0;
 return <Screen compact><AppHeader/><LoadState {...state}/>{!state.loading&&!state.error&&move&&<><View style={s.intro}><Text style={[styles.eyebrow,s.pathLabel]}>THE ROUTINE · WEEK {week} OF 4</Text><Text style={[styles.title,s.heading]}>A little move{`\n`}for today</Text><Text style={styles.body}>Just for you. Your partner gets their own.</Text></View>
  <View style={s.journey}><View style={s.journeyHead}><View style={{flex:1}}><Text style={s.kicker}>WEEK {week}</Text><Text style={s.weekTitle}>{chapters[week-1]}</Text></View><Text style={s.dayCount}>DAY {dayInWeek} / 7</Text></View><View style={s.timeline}>{dayLabels.map((label,index)=>{const day=index+1,past=day<dayInWeek,today=day===dayInWeek;return <View key={`${label}-${index}`} style={s.day}><View style={[s.marker,past&&s.markerPast,today&&s.markerToday]}>{past&&<Text style={s.check}>✓</Text>}{today&&<View style={s.dot}/>}</View><Text style={[s.dayLabel,today&&s.dayLabelToday]}>{label}</Text></View>})}</View><Text style={s.hint}>{dayInWeek<7?'Another little move is waiting tomorrow.':'A new chapter begins next week.'}</Text></View>
  <View style={[styles.card,s.moveCard]}><View style={s.row}><Text style={styles.eyebrow}>{primary?'FOR YOU TODAY':'A LITTLE MORE'}</Text><View style={s.pill}><Text style={styles.small}>{move.task_minutes} min</Text></View></View><Text style={[styles.cardTitle,s.moveTitle]}>{move.task_title}</Text><Text style={[styles.body,{lineHeight:24,marginBottom:20}]}>{move.task_body}</Text>{move.status==='completed'?<View style={s.done}><Text style={s.doneTitle}>A little something just grew.</Text><Text style={s.doneBody}>Your move is now part of your garden.</Text><Button label="See what grew" onPress={()=>router.navigate('/garden')}/></View>:<Button label="I did it" busy={busy} onPress={()=>{void complete();}}/>}</View>
  {move.status==='completed'&&move.slot<2&&<View style={s.bonus}><Text style={s.bonusPrompt}>Still feel like doing a little more?</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>{void oneMore();}} style={{minHeight:44,justifyContent:'center',opacity:busy?.5:1}}><Text style={s.bonusLink}>{busy?'A moment…':'Optional: give me another little move'}</Text></Pressable></View>}{move.status==='completed'&&move.slot>=2&&<Text style={[styles.small,s.bonus]}>That’s plenty for today.</Text>}{error&&<><Notice>{error}</Notice><Button label="Try again" secondary disabled={busy} onPress={()=>{setError(null);void state.refresh();}}/></>}</>}</Screen>;
}
const s=StyleSheet.create({intro:{marginTop:28},pathLabel:{letterSpacing:1.35,marginBottom:12},heading:{fontSize:40,lineHeight:43,letterSpacing:-1.3,marginBottom:12},journey:{marginTop:26,padding:18,borderWidth:1,borderColor:'#DED7CA',borderRadius:24,backgroundColor:'#FBF8F2'},journeyHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:16},kicker:{fontSize:10,lineHeight:14,letterSpacing:1.5,fontWeight:'700',color:'#728978'},weekTitle:{marginTop:4,fontFamily:'Georgia',fontSize:19,lineHeight:24,color:'#34483C'},dayCount:{fontSize:10,lineHeight:14,letterSpacing:1.1,color:'#9A9186'},timeline:{flexDirection:'row',marginTop:22},day:{flex:1,alignItems:'center'},marker:{width:22,height:22,borderRadius:11,borderWidth:1,borderColor:'#CEC7BB',backgroundColor:'#FBF8F2',alignItems:'center',justifyContent:'center'},markerPast:{borderColor:'#718675',backgroundColor:'#718675'},markerToday:{width:27,height:27,borderRadius:14,borderColor:'#718675',backgroundColor:'#EEF1E9'},check:{color:'#fff',fontSize:11,fontWeight:'700'},dot:{width:8,height:8,borderRadius:4,backgroundColor:'#718675'},dayLabel:{marginTop:5,fontSize:10,color:'#9B9388'},dayLabelToday:{color:'#405448',fontWeight:'700'},hint:{marginTop:16,fontSize:12,lineHeight:18,color:'#8A8278',textAlign:'center'},moveCard:{marginTop:20,padding:22,borderRadius:26},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},pill:{backgroundColor:'#F1ECE4',borderRadius:999,paddingHorizontal:10,paddingVertical:7},moveTitle:{fontSize:28,lineHeight:32,marginTop:16,marginBottom:12},done:{gap:8},doneTitle:{fontFamily:'Georgia',fontSize:20,lineHeight:25,color:'#34483C'},doneBody:{fontSize:13,lineHeight:19,color:'#847C72',marginBottom:6},bonus:{marginTop:18,paddingHorizontal:4,marginBottom:20},bonusPrompt:{fontFamily:'Georgia',fontSize:16,lineHeight:22,color:'#4A5A50'},bonusLink:{color:'#8A8278',fontSize:13,fontWeight:'600'}});