-- Follow-up QA: reduce semantic duplication and improve week-specific personalization.
update private.task_catalogue c
set title=v.title,body=v.body,why_it_matters=v.why_it_matters,mechanisms=v.mechanisms,
    contexts=v.contexts,effort=v.effort,requires_partner_cooperation=v.requires_partner_cooperation,
    repeatability=v.repeatability,keeper_potential=v.keeper_potential,theme_weights=v.theme_weights,
    exclusions=v.exclusions,personalization_weights=v.personalization_weights
from (values
('RTN012','Choose for each other','Get a coffee, snack, or treat together and choose for each other. Keep it within things you already know the other person likes.','A low-stakes change to a familiar choice introduces novelty and attention without requiring a special date.',ARRAY['novelty','curiosity','behavioral_experiment']::text[],ARRAY['cafe_or_bar','restaurant','shopping_or_errands']::text[],2,true,'low','low','{"routine":0.9,"spark":0.7}'::jsonb,ARRAY['dietary_or_financial_constraints']::text[],'{"anticipation":0.35,"curiosity":0.4,"novelty":1,"spontaneity":0.65}'::jsonb),
('RTN019','Bring back a song','Play one song connected to a good shared memory. Ask what they remember about that time.','A familiar song can pull an old shared moment back into the room and give you something real to talk about.',ARRAY['positive_affect','cue_association']::text[],ARRAY['home','car','walking','text_or_remote']::text[],1,false,'high','high','{"routine":0.7,"spark":0.8,"closeness":0.6}'::jsonb,ARRAY['painful_memory_association']::text[],'{"anticipation":0.35,"curiosity":0.6,"emotional_conversation":0.8,"verbal_affection":0.3}'::jsonb),
('RTN028','What else could it mean?','Catch one moment when you decide what your partner meant. Ask yourself, “What else could this mean?” before responding.','The first meaning you give a comment is not always the only one. Another plausible reading can change your next response.',ARRAY['alternative_interpretation','pause_before_response']::text[],ARRAY['home','workday','text_or_remote','anywhere']::text[],1,false,'high','high','{"routine":0.7,"conflict":0.9,"communication":0.7}'::jsonb,ARRAY['clear_boundary_violation']::text[],'{"curiosity":0.7,"emotional_conversation":0.35,"support":0.25}'::jsonb),
('RTN035','Bring back your shared humor','Bring one piece of shared humor into an ordinary moment today: an old callback, a silly voice, a meme, or a joke you both already like.','Shared humor can interrupt a serious, practical rhythm and remind you that the two of you have more than one way of being together.',ARRAY['positive_affect','response_substitution','playfulness']::text[],ARRAY['home','workday','text_or_remote','anywhere']::text[],1,false,'high','medium','{"routine":0.8,"spark":0.8,"closeness":0.5}'::jsonb,ARRAY['acute_conflict']::text[],'{"playfulness":1,"spontaneity":0.6,"verbal_affection":0.2}'::jsonb),
('RTN038','Reset outside','Take a ten-minute walk together when the mood at home feels stuck. Leave the problem indoors for the first five minutes.','A change of setting can loosen a mood that has started to feel stuck.',ARRAY['environmental_design','behavioral_experiment','shared_activity']::text[],ARRAY['home','walking','outdoors']::text[],2,true,'medium','medium','{"routine":0.8,"conflict":0.5,"closeness":0.5}'::jsonb,ARRAY['unsafe_conflict_or_mobility_constraints']::text[],'{"novelty":0.6,"shared_experience":1,"spontaneity":0.45}'::jsonb),
('RTN039','A warmer goodbye','Before one separation today, make the goodbye warmer than usual. Use a form of affection that is already normal and welcome between you, then name one thing you''re looking forward to later.','A warmer goodbye gives an ordinary transition some attention and creates a reason to look forward to reconnecting.',ARRAY['cue_association','attention','positive_affect']::text[],ARRAY['home','workday','commuting','travel']::text[],1,true,'high','high','{"routine":0.9,"closeness":0.7}'::jsonb,ARRAY['touch_not_welcome']::text[],'{"anticipation":0.8,"physical_affection":1,"quality_attention":0.4,"verbal_affection":0.55}'::jsonb)
) as v(task_key,title,body,why_it_matters,mechanisms,contexts,effort,requires_partner_cooperation,repeatability,keeper_potential,theme_weights,exclusions,personalization_weights)
where c.task_key=v.task_key and c.content_version=2;
